"""Epistemic model for WIZZLE adversarial experiments.

Distinguishes:
- Observation: What actually happened (verifiable facts)
- Interpretation: What that might mean (one or more possible meanings)
- Conclusion: What Ghost concluded (or should have concluded)
- Entitlement: What evidence justifies what conclusion

This model ensures WIZZLE's judgment is independent of Ghost's conclusion.
"""

from enum import Enum, auto
from dataclasses import dataclass, field
from typing import Set, Optional, List

class EvidenceProvenance(Enum):
    """How we know a piece of evidence."""
    CONSTRUCTED = auto()      # Generated by WIZZLE during history creation
    OBSERVED = auto()         # Read from actual git/files
    DERIVED = auto()          # Computed from other evidence
    TARGET_REPORTED = auto()  # Ghost reported this finding
    DECLARED = auto()         # Explicitly stated in test setup
    HISTORICAL = auto()       # From git history
    UNASKABLE = auto()        # Cannot be determined

class FactualCorrectness(Enum):
    """Did Ghost correctly identify what happened?"""
    CORRECT = auto()          # Yes, the observation is accurate
    INCORRECT = auto()        # No, Ghost misread the evidence
    PARTIALLY_CORRECT = auto()  # Correct about some aspects
    UNASKABLE = auto()        # Cannot determine independently

class SemanticCorrectness(Enum):
    """Is Ghost's interpretation justified by the evidence?"""
    JUSTIFIED = auto()        # Yes, evidence entitles this conclusion
    OVERCLAIMED = auto()       # No, Ghost exceeded entitlement
    UNDERCLAIMED = auto()      # Ghost was too conservative
    CONTRADICTED = auto()      # Evidence actually contradicts conclusion
    INCONCLUSIVE = auto()      # Evidence doesn't determine answer
    UNASKABLE = auto()        # Cannot judge independently

class IntentKind(Enum):
    """Semantic categorization of why something happened."""
    ACCIDENTAL_REMOVAL = auto()
    INTENTIONAL_REFACTOR = auto()
    SECURITY_FIX = auto()
    DEAD_CODE_CLEANUP = auto()
    API_DEPRECATION = auto()
    TEST_ONLY_MIGRATION = auto()
    COMPATIBILITY_MIGRATION = auto()
    REPLACEMENT_BY_NEW_MEMBER = auto()
    PARTIAL_MIGRATION = auto()
    TEMPORARY_EXPERIMENT = auto()
    REVERT = auto()
    CHERRY_PICK = auto()
    BACKPORT = auto()
    BRANCH_DIVERGENCE = auto()
    RELEASE_ONLY_CHANGE = auto()
    UNKNOWN_INTENT = auto()

class EvidenceStrength(Enum):
    """How reliably does this evidence point to an interpretation?"""
    STRUCTURAL = auto()       # Mechanically definitive (e.g., object exists)
    HISTORICAL = auto()       # From verifiable git history
    DECLARATIVE = auto()      # Explicitly stated in code/docs
    DERIVED = auto()          # Computed from other evidence
    WEAK_INTENT_SIGNAL = auto()  # Suggestive but not definitive
    NON_AUTHORITATIVE = auto()   # Unreliable signal (e.g., user-provided)

@dataclass
class ObservedFact:
    """An objectively verifiable fact about the repository."""
    description: str
    provenance: EvidenceProvenance
    verified: bool = False
    source: Optional[str] = None

@dataclass
class InterpretationHypothesis:
    """A possible interpretation of observations."""
    intent_kind: IntentKind
    supporting_evidence: List[ObservedFact] = field(default_factory=list)
    contradicting_evidence: List[ObservedFact] = field(default_factory=list)
    likelihood: float = 0.5  # 0.0-1.0, if determinable

@dataclass
class SemanticTruth:
    """Ground truth about what actually happened (independent of Ghost)."""
    primary_intent: IntentKind
    alternative_intents: List[InterpretationHypothesis] = field(default_factory=list)
    confidence: float = 1.0
    notes: str = ""

@dataclass
class GhostObservation:
    """What Ghost reported observing."""
    member_name: str
    provenance_class: str  # e.g., "REMOVED_FROM_LIBRARY"
    severity: str          # e.g., "MAJOR"
    evidence_cited: List[str] = field(default_factory=list)

@dataclass
class EvidenceEntitlement:
    """What evidence would justify a particular conclusion."""
    conclusion: str
    required_evidence: Set[str] = field(default_factory=set)
    sufficient_evidence: Set[str] = field(default_factory=set)
    contradicted_by: Set[str] = field(default_factory=set)

@dataclass
class ExperimentResult:
    """Complete record of one adversarial experiment."""
    case_id: str
    world_name: str
    
    # What happened
    observations: List[ObservedFact] = field(default_factory=list)
    
    # What it means
    semantic_truth: Optional[SemanticTruth] = None
    
    # What Ghost concluded
    ghost_conclusion: Optional[GhostObservation] = None
    
    # Judgment
    factual_correctness: FactualCorrectness = FactualCorrectness.UNASKABLE
    semantic_correctness: SemanticCorrectness = SemanticCorrectness.UNASKABLE
    
    # Evidence analysis
    entitlements: List[EvidenceEntitlement] = field(default_factory=list)
    overclaim: bool = False
    underclaim: bool = False
    
    # Reproducibility
    world_digest: Optional[str] = None
    history_digest: Optional[str] = None
    semantic_digest: Optional[str] = None
    
    # Evaluation
    holdout_status: Optional[str] = None  # DISCOVERY, HOLDOUT, REGRESSION
    minimized_case: Optional[str] = None
    human_review_required: bool = False
    
    # Notes
    notes: str = ""
